name: mentoria
description: "MentorIA – Tu compañero inteligente de progreso"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter
  supabase: ^2.0.0
  supabase_flutter: ^2.0.0
  image_picker: ^1.0.0
  image: ^4.0.0
  google_fonts: ^6.1.0
  provider: ^6.1.1
  flutter_animate: ^4.5.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  blur: ^3.1.0
  rive: ^0.13.0
  http: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/